JETUT-72 catch up servlet and faces hello world as per changes in tutorial
eclipse-ee4j/jakartaee-examples pull request #80
Opened 2023-08-21 14:20 UTC by BalusC

2023-11-27 15:00 UTC, kito99 commented
@arjantijms please review

2023-12-11 16:03 UTC, kito99 commented
@mnriem can you review?

2023-12-11 20:35 UTC, mnriem requested changes

2023-12-12 14:34 UTC, kito99 commented
thanks @mnriem!

2023-12-22 22:30 UTC, mnriem commented
@kito99 Do you need more from my end?

2024-01-03 18:48 UTC, kito99 commented
@mnriem I think we're good. thanks! 

@BalusC this is in your court, now.

2024-05-10 10:07 UTC, BalusC commented on tutorial/README.md
> +* Windows: `%HOMEDRIVE%%HOMEPATH%\glassfish7`
Okay.

2024-05-10 10:08 UTC, BalusC commented on tutorial/pom.xml
> +                                    <version>[11,)</version>
Not understanding. Please elaborate (with an example).

2024-05-10 10:09 UTC, BalusC commented on tutorial/pom.xml
> +                    <source>11</source>
Not understanding. It's already 11. Please elaborate.

2024-05-10 10:15 UTC, BalusC commented on tutorial/pom.xml
> +        <glassfish.home>${user.home}/glassfish7</glassfish.home>
Okay, adjusted, but it didn't work for me. I'll need to look closer at that later.

2024-06-27 19:52 UTC, merged